module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: [
    '<rootDir>/src',
    '<rootDir>/tests',
    '<rootDir>/commands',
    '<rootDir>/../supabase',
    '<rootDir>/utils',
  ],
  testMatch: ['**/*.test.ts', '**/*.test.js'],
  collectCoverageFrom: [
    'src/**/*.ts',
    'commands/**/*.ts',
    '../supabase/**/*.ts',
    'utils/**/*.ts',
    '!**/*.d.ts',
    '!**/node_modules/**',
    '!**/dist/**',
    '!**/coverage/**',
    '!**/*.test.ts',
    '!tests/**',
    // Process entrypoints + thin SDK wrappers — tested end-to-end in Discord,
    // not unit-testable without elaborate SDK mocking that provides no signal.
    '!src/bot.ts',
    '!src/deploy-commands.ts',
    '!utils/googleServices.ts',
  ],
  coveragePathIgnorePatterns: [
    '/node_modules/',
    '<rootDir>/src/bot.ts',
    '<rootDir>/src/deploy-commands.ts',
    '<rootDir>/utils/googleServices.ts',
  ],
  moduleNameMapper: {
    '^@shared/(.*)$': '<rootDir>/shared/$1',
    '^@database/(.*)$': '<rootDir>/../supabase/$1',
    '^@utils/(.*)$': '<rootDir>/utils/$1',
    '^@commands/(.*)$': '<rootDir>/commands/$1',
    '^@config/(.*)$': '<rootDir>/config/$1',
    '^@src/(.*)$': '<rootDir>/src/$1',
    '^@types/(.*)$': '<rootDir>/types/$1',
    '^@/(.*)$': '<rootDir>/$1',
  },
  setupFilesAfterEnv: ['<rootDir>/tests/setup.ts'],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'html', 'json-summary'],
  coverageThreshold: {
    global: {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80,
    },
  },
  testTimeout: 10000,
  transform: {
    '^.+\\.ts$': [
      'ts-jest',
      {
        tsconfig: {
          esModuleInterop: true,
          allowJs: true,
          moduleResolution: 'node',
          isolatedModules: true,
        },
      },
    ],
  },
  transformIgnorePatterns: ['node_modules/(?!(@octokit)/)'],
};
